title:               Seohyeon Cha
url:                 https://seohyeon-cha.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Seohyeon Cha
  url:               seohyeon-cha.github.io
  email:             kaitjgus@kaist.ac.kr

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
